<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260606122742 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE academic_group (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, group_number INT NOT NULL, level_id INT NOT NULL, program_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_998829005FB14BA7 ON academic_group (level_id)');
        $this->addSql('CREATE INDEX IDX_998829003EB8070A ON academic_group (program_id)');
        $this->addSql('CREATE TABLE course_session (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(20) NOT NULL, teacher_id INT NOT NULL, subject_id INT NOT NULL, room_id INT NOT NULL, time_slot_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D887D03841807E1D ON course_session (teacher_id)');
        $this->addSql('CREATE INDEX IDX_D887D03823EDC87 ON course_session (subject_id)');
        $this->addSql('CREATE INDEX IDX_D887D03854177093 ON course_session (room_id)');
        $this->addSql('CREATE INDEX IDX_D887D038D62B0FA ON course_session (time_slot_id)');
        $this->addSql('CREATE TABLE course_session_academic_group (course_session_id INT NOT NULL, academic_group_id INT NOT NULL, PRIMARY KEY (course_session_id, academic_group_id))');
        $this->addSql('CREATE INDEX IDX_650E5DFBBEDDA25C ON course_session_academic_group (course_session_id)');
        $this->addSql('CREATE INDEX IDX_650E5DFBC1645150 ON course_session_academic_group (academic_group_id)');
        $this->addSql('CREATE TABLE level (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(10) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9AEACC1377153098 ON level (code)');
        $this->addSql('CREATE TABLE program (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(50) NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_92ED778477153098 ON program (code)');
        $this->addSql('CREATE TABLE room (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(50) NOT NULL, name VARCHAR(255) NOT NULL, type VARCHAR(50) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_729F519B77153098 ON room (code)');
        $this->addSql('CREATE TABLE subject (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(50) NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FBCE3E7A77153098 ON subject (code)');
        $this->addSql('CREATE TABLE teacher (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) DEFAULT NULL, email VARCHAR(255) NOT NULL, is_active BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B0F6A6D5E7927C74 ON teacher (email)');
        $this->addSql('CREATE TABLE time_slot (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, day_of_week VARCHAR(20) NOT NULL, start_time TIME(0) WITHOUT TIME ZONE NOT NULL, end_time TIME(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE academic_group ADD CONSTRAINT FK_998829005FB14BA7 FOREIGN KEY (level_id) REFERENCES level (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE academic_group ADD CONSTRAINT FK_998829003EB8070A FOREIGN KEY (program_id) REFERENCES program (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE course_session ADD CONSTRAINT FK_D887D03841807E1D FOREIGN KEY (teacher_id) REFERENCES teacher (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE course_session ADD CONSTRAINT FK_D887D03823EDC87 FOREIGN KEY (subject_id) REFERENCES subject (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE course_session ADD CONSTRAINT FK_D887D03854177093 FOREIGN KEY (room_id) REFERENCES room (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE course_session ADD CONSTRAINT FK_D887D038D62B0FA FOREIGN KEY (time_slot_id) REFERENCES time_slot (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE course_session_academic_group ADD CONSTRAINT FK_650E5DFBBEDDA25C FOREIGN KEY (course_session_id) REFERENCES course_session (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE course_session_academic_group ADD CONSTRAINT FK_650E5DFBC1645150 FOREIGN KEY (academic_group_id) REFERENCES academic_group (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE academic_group DROP CONSTRAINT FK_998829005FB14BA7');
        $this->addSql('ALTER TABLE academic_group DROP CONSTRAINT FK_998829003EB8070A');
        $this->addSql('ALTER TABLE course_session DROP CONSTRAINT FK_D887D03841807E1D');
        $this->addSql('ALTER TABLE course_session DROP CONSTRAINT FK_D887D03823EDC87');
        $this->addSql('ALTER TABLE course_session DROP CONSTRAINT FK_D887D03854177093');
        $this->addSql('ALTER TABLE course_session DROP CONSTRAINT FK_D887D038D62B0FA');
        $this->addSql('ALTER TABLE course_session_academic_group DROP CONSTRAINT FK_650E5DFBBEDDA25C');
        $this->addSql('ALTER TABLE course_session_academic_group DROP CONSTRAINT FK_650E5DFBC1645150');
        $this->addSql('DROP TABLE academic_group');
        $this->addSql('DROP TABLE course_session');
        $this->addSql('DROP TABLE course_session_academic_group');
        $this->addSql('DROP TABLE level');
        $this->addSql('DROP TABLE program');
        $this->addSql('DROP TABLE room');
        $this->addSql('DROP TABLE subject');
        $this->addSql('DROP TABLE teacher');
        $this->addSql('DROP TABLE time_slot');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
