<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260606140124 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE schedule_week (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, start_date DATE NOT NULL, end_date DATE NOT NULL, status VARCHAR(20) NOT NULL, published_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_BB12499B95275AB8 ON schedule_week (start_date)');
        $this->addSql('ALTER TABLE course_session ADD schedule_week_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE course_session ADD CONSTRAINT FK_D887D0384505179E FOREIGN KEY (schedule_week_id) REFERENCES schedule_week (id)');
        $this->addSql('CREATE INDEX IDX_D887D0384505179E ON course_session (schedule_week_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE schedule_week');
        $this->addSql('ALTER TABLE course_session DROP CONSTRAINT FK_D887D0384505179E');
        $this->addSql('DROP INDEX IDX_D887D0384505179E');
        $this->addSql('ALTER TABLE course_session DROP schedule_week_id');
    }
}
